/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as SurpriseRouteImport } from './routes/surprise'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MindRouteImport } from './routes/mind'
import { Route as MeRouteImport } from './routes/me'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as DietRouteImport } from './routes/diet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as SpeechIndexRouteImport } from './routes/speech/index'
import { Route as BrainIndexRouteImport } from './routes/brain/index'
import { Route as ArchetypesIndexRouteImport } from './routes/archetypes/index'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as SpeechRulesRouteImport } from './routes/speech/rules'
import { Route as SpeechProblemsRouteImport } from './routes/speech/problems'
import { Route as SpeechMonologueRouteImport } from './routes/speech/monologue'
import { Route as NoteSplatRouteImport } from './routes/note.$'
import { Route as FolderSplatRouteImport } from './routes/folder.$'
import { Route as ChatPersonaRouteImport } from './routes/chat.$persona'
import { Route as BrainHistoryRouteImport } from './routes/brain/history'
import { Route as ArchetypesSlugRouteImport } from './routes/archetypes/$slug'
import { Route as SpeechDrillIdRouteImport } from './routes/speech/drill.$id'
import { Route as BrainStudioLaneRouteImport } from './routes/brain/studio.$lane'
import { Route as BrainDrillIdRouteImport } from './routes/brain/drill.$id'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const SurpriseRoute = SurpriseRouteImport.update({
  id: '/surprise',
  path: '/surprise',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MindRoute = MindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechIndexRoute = SpeechIndexRouteImport.update({
  id: '/speech/',
  path: '/speech/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainIndexRoute = BrainIndexRouteImport.update({
  id: '/brain/',
  path: '/brain/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchetypesIndexRoute = ArchetypesIndexRouteImport.update({
  id: '/archetypes/',
  path: '/archetypes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechRulesRoute = SpeechRulesRouteImport.update({
  id: '/speech/rules',
  path: '/speech/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechProblemsRoute = SpeechProblemsRouteImport.update({
  id: '/speech/problems',
  path: '/speech/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechMonologueRoute = SpeechMonologueRouteImport.update({
  id: '/speech/monologue',
  path: '/speech/monologue',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteSplatRoute = NoteSplatRouteImport.update({
  id: '/note/$',
  path: '/note/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderSplatRoute = FolderSplatRouteImport.update({
  id: '/folder/$',
  path: '/folder/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPersonaRoute = ChatPersonaRouteImport.update({
  id: '/chat/$persona',
  path: '/chat/$persona',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainHistoryRoute = BrainHistoryRouteImport.update({
  id: '/brain/history',
  path: '/brain/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchetypesSlugRoute = ArchetypesSlugRouteImport.update({
  id: '/archetypes/$slug',
  path: '/archetypes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechDrillIdRoute = SpeechDrillIdRouteImport.update({
  id: '/speech/drill/$id',
  path: '/speech/drill/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainStudioLaneRoute = BrainStudioLaneRouteImport.update({
  id: '/brain/studio/$lane',
  path: '/brain/studio/$lane',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainDrillIdRoute = BrainDrillIdRouteImport.update({
  id: '/brain/drill/$id',
  path: '/brain/drill/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diet': typeof DietRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/me': typeof MeRoute
  '/mind': typeof MindRoute
  '/settings': typeof SettingsRoute
  '/surprise': typeof SurpriseRoute
  '/watch': typeof WatchRoute
  '/archetypes/$slug': typeof ArchetypesSlugRoute
  '/brain/history': typeof BrainHistoryRoute
  '/chat/$persona': typeof ChatPersonaRoute
  '/folder/$': typeof FolderSplatRoute
  '/note/$': typeof NoteSplatRoute
  '/speech/monologue': typeof SpeechMonologueRoute
  '/speech/problems': typeof SpeechProblemsRoute
  '/speech/rules': typeof SpeechRulesRoute
  '/tasks/new': typeof TasksNewRoute
  '/archetypes/': typeof ArchetypesIndexRoute
  '/brain/': typeof BrainIndexRoute
  '/speech/': typeof SpeechIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/brain/drill/$id': typeof BrainDrillIdRoute
  '/brain/studio/$lane': typeof BrainStudioLaneRoute
  '/speech/drill/$id': typeof SpeechDrillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diet': typeof DietRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/me': typeof MeRoute
  '/mind': typeof MindRoute
  '/settings': typeof SettingsRoute
  '/surprise': typeof SurpriseRoute
  '/watch': typeof WatchRoute
  '/archetypes/$slug': typeof ArchetypesSlugRoute
  '/brain/history': typeof BrainHistoryRoute
  '/chat/$persona': typeof ChatPersonaRoute
  '/folder/$': typeof FolderSplatRoute
  '/note/$': typeof NoteSplatRoute
  '/speech/monologue': typeof SpeechMonologueRoute
  '/speech/problems': typeof SpeechProblemsRoute
  '/speech/rules': typeof SpeechRulesRoute
  '/tasks/new': typeof TasksNewRoute
  '/archetypes': typeof ArchetypesIndexRoute
  '/brain': typeof BrainIndexRoute
  '/speech': typeof SpeechIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/brain/drill/$id': typeof BrainDrillIdRoute
  '/brain/studio/$lane': typeof BrainStudioLaneRoute
  '/speech/drill/$id': typeof SpeechDrillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diet': typeof DietRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/me': typeof MeRoute
  '/mind': typeof MindRoute
  '/settings': typeof SettingsRoute
  '/surprise': typeof SurpriseRoute
  '/watch': typeof WatchRoute
  '/archetypes/$slug': typeof ArchetypesSlugRoute
  '/brain/history': typeof BrainHistoryRoute
  '/chat/$persona': typeof ChatPersonaRoute
  '/folder/$': typeof FolderSplatRoute
  '/note/$': typeof NoteSplatRoute
  '/speech/monologue': typeof SpeechMonologueRoute
  '/speech/problems': typeof SpeechProblemsRoute
  '/speech/rules': typeof SpeechRulesRoute
  '/tasks/new': typeof TasksNewRoute
  '/archetypes/': typeof ArchetypesIndexRoute
  '/brain/': typeof BrainIndexRoute
  '/speech/': typeof SpeechIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/brain/drill/$id': typeof BrainDrillIdRoute
  '/brain/studio/$lane': typeof BrainStudioLaneRoute
  '/speech/drill/$id': typeof SpeechDrillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diet'
    | '/journal'
    | '/library'
    | '/me'
    | '/mind'
    | '/settings'
    | '/surprise'
    | '/watch'
    | '/archetypes/$slug'
    | '/brain/history'
    | '/chat/$persona'
    | '/folder/$'
    | '/note/$'
    | '/speech/monologue'
    | '/speech/problems'
    | '/speech/rules'
    | '/tasks/new'
    | '/archetypes/'
    | '/brain/'
    | '/speech/'
    | '/tasks/'
    | '/brain/drill/$id'
    | '/brain/studio/$lane'
    | '/speech/drill/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diet'
    | '/journal'
    | '/library'
    | '/me'
    | '/mind'
    | '/settings'
    | '/surprise'
    | '/watch'
    | '/archetypes/$slug'
    | '/brain/history'
    | '/chat/$persona'
    | '/folder/$'
    | '/note/$'
    | '/speech/monologue'
    | '/speech/problems'
    | '/speech/rules'
    | '/tasks/new'
    | '/archetypes'
    | '/brain'
    | '/speech'
    | '/tasks'
    | '/brain/drill/$id'
    | '/brain/studio/$lane'
    | '/speech/drill/$id'
  id:
    | '__root__'
    | '/'
    | '/diet'
    | '/journal'
    | '/library'
    | '/me'
    | '/mind'
    | '/settings'
    | '/surprise'
    | '/watch'
    | '/archetypes/$slug'
    | '/brain/history'
    | '/chat/$persona'
    | '/folder/$'
    | '/note/$'
    | '/speech/monologue'
    | '/speech/problems'
    | '/speech/rules'
    | '/tasks/new'
    | '/archetypes/'
    | '/brain/'
    | '/speech/'
    | '/tasks/'
    | '/brain/drill/$id'
    | '/brain/studio/$lane'
    | '/speech/drill/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DietRoute: typeof DietRoute
  JournalRoute: typeof JournalRoute
  LibraryRoute: typeof LibraryRoute
  MeRoute: typeof MeRoute
  MindRoute: typeof MindRoute
  SettingsRoute: typeof SettingsRoute
  SurpriseRoute: typeof SurpriseRoute
  WatchRoute: typeof WatchRoute
  ArchetypesSlugRoute: typeof ArchetypesSlugRoute
  BrainHistoryRoute: typeof BrainHistoryRoute
  ChatPersonaRoute: typeof ChatPersonaRoute
  FolderSplatRoute: typeof FolderSplatRoute
  NoteSplatRoute: typeof NoteSplatRoute
  SpeechMonologueRoute: typeof SpeechMonologueRoute
  SpeechProblemsRoute: typeof SpeechProblemsRoute
  SpeechRulesRoute: typeof SpeechRulesRoute
  TasksNewRoute: typeof TasksNewRoute
  ArchetypesIndexRoute: typeof ArchetypesIndexRoute
  BrainIndexRoute: typeof BrainIndexRoute
  SpeechIndexRoute: typeof SpeechIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  BrainDrillIdRoute: typeof BrainDrillIdRoute
  BrainStudioLaneRoute: typeof BrainStudioLaneRoute
  SpeechDrillIdRoute: typeof SpeechDrillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surprise': {
      id: '/surprise'
      path: '/surprise'
      fullPath: '/surprise'
      preLoaderRoute: typeof SurpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mind': {
      id: '/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof MindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech/': {
      id: '/speech/'
      path: '/speech'
      fullPath: '/speech/'
      preLoaderRoute: typeof SpeechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain/': {
      id: '/brain/'
      path: '/brain'
      fullPath: '/brain/'
      preLoaderRoute: typeof BrainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archetypes/': {
      id: '/archetypes/'
      path: '/archetypes'
      fullPath: '/archetypes/'
      preLoaderRoute: typeof ArchetypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech/rules': {
      id: '/speech/rules'
      path: '/speech/rules'
      fullPath: '/speech/rules'
      preLoaderRoute: typeof SpeechRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech/problems': {
      id: '/speech/problems'
      path: '/speech/problems'
      fullPath: '/speech/problems'
      preLoaderRoute: typeof SpeechProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech/monologue': {
      id: '/speech/monologue'
      path: '/speech/monologue'
      fullPath: '/speech/monologue'
      preLoaderRoute: typeof SpeechMonologueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$': {
      id: '/note/$'
      path: '/note/$'
      fullPath: '/note/$'
      preLoaderRoute: typeof NoteSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder/$': {
      id: '/folder/$'
      path: '/folder/$'
      fullPath: '/folder/$'
      preLoaderRoute: typeof FolderSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$persona': {
      id: '/chat/$persona'
      path: '/chat/$persona'
      fullPath: '/chat/$persona'
      preLoaderRoute: typeof ChatPersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain/history': {
      id: '/brain/history'
      path: '/brain/history'
      fullPath: '/brain/history'
      preLoaderRoute: typeof BrainHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archetypes/$slug': {
      id: '/archetypes/$slug'
      path: '/archetypes/$slug'
      fullPath: '/archetypes/$slug'
      preLoaderRoute: typeof ArchetypesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech/drill/$id': {
      id: '/speech/drill/$id'
      path: '/speech/drill/$id'
      fullPath: '/speech/drill/$id'
      preLoaderRoute: typeof SpeechDrillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain/studio/$lane': {
      id: '/brain/studio/$lane'
      path: '/brain/studio/$lane'
      fullPath: '/brain/studio/$lane'
      preLoaderRoute: typeof BrainStudioLaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain/drill/$id': {
      id: '/brain/drill/$id'
      path: '/brain/drill/$id'
      fullPath: '/brain/drill/$id'
      preLoaderRoute: typeof BrainDrillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DietRoute: DietRoute,
  JournalRoute: JournalRoute,
  LibraryRoute: LibraryRoute,
  MeRoute: MeRoute,
  MindRoute: MindRoute,
  SettingsRoute: SettingsRoute,
  SurpriseRoute: SurpriseRoute,
  WatchRoute: WatchRoute,
  ArchetypesSlugRoute: ArchetypesSlugRoute,
  BrainHistoryRoute: BrainHistoryRoute,
  ChatPersonaRoute: ChatPersonaRoute,
  FolderSplatRoute: FolderSplatRoute,
  NoteSplatRoute: NoteSplatRoute,
  SpeechMonologueRoute: SpeechMonologueRoute,
  SpeechProblemsRoute: SpeechProblemsRoute,
  SpeechRulesRoute: SpeechRulesRoute,
  TasksNewRoute: TasksNewRoute,
  ArchetypesIndexRoute: ArchetypesIndexRoute,
  BrainIndexRoute: BrainIndexRoute,
  SpeechIndexRoute: SpeechIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  BrainDrillIdRoute: BrainDrillIdRoute,
  BrainStudioLaneRoute: BrainStudioLaneRoute,
  SpeechDrillIdRoute: SpeechDrillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
