/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as SurpriseRouteImport } from './routes/surprise'
import { Route as SpeechRouteImport } from './routes/speech'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as DietRouteImport } from './routes/diet'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as ArchetypesRouteImport } from './routes/archetypes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoteSplatRouteImport } from './routes/note.$'
import { Route as FolderSplatRouteImport } from './routes/folder.$'
import { Route as BrainHistoryRouteImport } from './routes/brain.history'
import { Route as ArchetypesSlugRouteImport } from './routes/archetypes.$slug'
import { Route as SpeechDrillIdRouteImport } from './routes/speech.drill.$id'
import { Route as BrainStudioLaneRouteImport } from './routes/brain.studio.$lane'
import { Route as BrainDrillIdRouteImport } from './routes/brain.drill.$id'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const SurpriseRoute = SurpriseRouteImport.update({
  id: '/surprise',
  path: '/surprise',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechRoute = SpeechRouteImport.update({
  id: '/speech',
  path: '/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchetypesRoute = ArchetypesRouteImport.update({
  id: '/archetypes',
  path: '/archetypes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteSplatRoute = NoteSplatRouteImport.update({
  id: '/note/$',
  path: '/note/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderSplatRoute = FolderSplatRouteImport.update({
  id: '/folder/$',
  path: '/folder/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainHistoryRoute = BrainHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BrainRoute,
} as any)
const ArchetypesSlugRoute = ArchetypesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArchetypesRoute,
} as any)
const SpeechDrillIdRoute = SpeechDrillIdRouteImport.update({
  id: '/drill/$id',
  path: '/drill/$id',
  getParentRoute: () => SpeechRoute,
} as any)
const BrainStudioLaneRoute = BrainStudioLaneRouteImport.update({
  id: '/studio/$lane',
  path: '/studio/$lane',
  getParentRoute: () => BrainRoute,
} as any)
const BrainDrillIdRoute = BrainDrillIdRouteImport.update({
  id: '/drill/$id',
  path: '/drill/$id',
  getParentRoute: () => BrainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRouteWithChildren
  '/brain': typeof BrainRouteWithChildren
  '/diet': typeof DietRoute
  '/journal': typeof JournalRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/speech': typeof SpeechRouteWithChildren
  '/surprise': typeof SurpriseRoute
  '/watch': typeof WatchRoute
  '/archetypes/$slug': typeof ArchetypesSlugRoute
  '/brain/history': typeof BrainHistoryRoute
  '/folder/$': typeof FolderSplatRoute
  '/note/$': typeof NoteSplatRoute
  '/brain/drill/$id': typeof BrainDrillIdRoute
  '/brain/studio/$lane': typeof BrainStudioLaneRoute
  '/speech/drill/$id': typeof SpeechDrillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRouteWithChildren
  '/brain': typeof BrainRouteWithChildren
  '/diet': typeof DietRoute
  '/journal': typeof JournalRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/speech': typeof SpeechRouteWithChildren
  '/surprise': typeof SurpriseRoute
  '/watch': typeof WatchRoute
  '/archetypes/$slug': typeof ArchetypesSlugRoute
  '/brain/history': typeof BrainHistoryRoute
  '/folder/$': typeof FolderSplatRoute
  '/note/$': typeof NoteSplatRoute
  '/brain/drill/$id': typeof BrainDrillIdRoute
  '/brain/studio/$lane': typeof BrainStudioLaneRoute
  '/speech/drill/$id': typeof SpeechDrillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRouteWithChildren
  '/brain': typeof BrainRouteWithChildren
  '/diet': typeof DietRoute
  '/journal': typeof JournalRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/speech': typeof SpeechRouteWithChildren
  '/surprise': typeof SurpriseRoute
  '/watch': typeof WatchRoute
  '/archetypes/$slug': typeof ArchetypesSlugRoute
  '/brain/history': typeof BrainHistoryRoute
  '/folder/$': typeof FolderSplatRoute
  '/note/$': typeof NoteSplatRoute
  '/brain/drill/$id': typeof BrainDrillIdRoute
  '/brain/studio/$lane': typeof BrainStudioLaneRoute
  '/speech/drill/$id': typeof SpeechDrillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archetypes'
    | '/brain'
    | '/diet'
    | '/journal'
    | '/missions'
    | '/profile'
    | '/settings'
    | '/speech'
    | '/surprise'
    | '/watch'
    | '/archetypes/$slug'
    | '/brain/history'
    | '/folder/$'
    | '/note/$'
    | '/brain/drill/$id'
    | '/brain/studio/$lane'
    | '/speech/drill/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archetypes'
    | '/brain'
    | '/diet'
    | '/journal'
    | '/missions'
    | '/profile'
    | '/settings'
    | '/speech'
    | '/surprise'
    | '/watch'
    | '/archetypes/$slug'
    | '/brain/history'
    | '/folder/$'
    | '/note/$'
    | '/brain/drill/$id'
    | '/brain/studio/$lane'
    | '/speech/drill/$id'
  id:
    | '__root__'
    | '/'
    | '/archetypes'
    | '/brain'
    | '/diet'
    | '/journal'
    | '/missions'
    | '/profile'
    | '/settings'
    | '/speech'
    | '/surprise'
    | '/watch'
    | '/archetypes/$slug'
    | '/brain/history'
    | '/folder/$'
    | '/note/$'
    | '/brain/drill/$id'
    | '/brain/studio/$lane'
    | '/speech/drill/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchetypesRoute: typeof ArchetypesRouteWithChildren
  BrainRoute: typeof BrainRouteWithChildren
  DietRoute: typeof DietRoute
  JournalRoute: typeof JournalRoute
  MissionsRoute: typeof MissionsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SpeechRoute: typeof SpeechRouteWithChildren
  SurpriseRoute: typeof SurpriseRoute
  WatchRoute: typeof WatchRoute
  FolderSplatRoute: typeof FolderSplatRoute
  NoteSplatRoute: typeof NoteSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surprise': {
      id: '/surprise'
      path: '/surprise'
      fullPath: '/surprise'
      preLoaderRoute: typeof SurpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech': {
      id: '/speech'
      path: '/speech'
      fullPath: '/speech'
      preLoaderRoute: typeof SpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archetypes': {
      id: '/archetypes'
      path: '/archetypes'
      fullPath: '/archetypes'
      preLoaderRoute: typeof ArchetypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$': {
      id: '/note/$'
      path: '/note/$'
      fullPath: '/note/$'
      preLoaderRoute: typeof NoteSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder/$': {
      id: '/folder/$'
      path: '/folder/$'
      fullPath: '/folder/$'
      preLoaderRoute: typeof FolderSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain/history': {
      id: '/brain/history'
      path: '/history'
      fullPath: '/brain/history'
      preLoaderRoute: typeof BrainHistoryRouteImport
      parentRoute: typeof BrainRoute
    }
    '/archetypes/$slug': {
      id: '/archetypes/$slug'
      path: '/$slug'
      fullPath: '/archetypes/$slug'
      preLoaderRoute: typeof ArchetypesSlugRouteImport
      parentRoute: typeof ArchetypesRoute
    }
    '/speech/drill/$id': {
      id: '/speech/drill/$id'
      path: '/drill/$id'
      fullPath: '/speech/drill/$id'
      preLoaderRoute: typeof SpeechDrillIdRouteImport
      parentRoute: typeof SpeechRoute
    }
    '/brain/studio/$lane': {
      id: '/brain/studio/$lane'
      path: '/studio/$lane'
      fullPath: '/brain/studio/$lane'
      preLoaderRoute: typeof BrainStudioLaneRouteImport
      parentRoute: typeof BrainRoute
    }
    '/brain/drill/$id': {
      id: '/brain/drill/$id'
      path: '/drill/$id'
      fullPath: '/brain/drill/$id'
      preLoaderRoute: typeof BrainDrillIdRouteImport
      parentRoute: typeof BrainRoute
    }
  }
}

interface ArchetypesRouteChildren {
  ArchetypesSlugRoute: typeof ArchetypesSlugRoute
}

const ArchetypesRouteChildren: ArchetypesRouteChildren = {
  ArchetypesSlugRoute: ArchetypesSlugRoute,
}

const ArchetypesRouteWithChildren = ArchetypesRoute._addFileChildren(
  ArchetypesRouteChildren,
)

interface BrainRouteChildren {
  BrainHistoryRoute: typeof BrainHistoryRoute
  BrainDrillIdRoute: typeof BrainDrillIdRoute
  BrainStudioLaneRoute: typeof BrainStudioLaneRoute
}

const BrainRouteChildren: BrainRouteChildren = {
  BrainHistoryRoute: BrainHistoryRoute,
  BrainDrillIdRoute: BrainDrillIdRoute,
  BrainStudioLaneRoute: BrainStudioLaneRoute,
}

const BrainRouteWithChildren = BrainRoute._addFileChildren(BrainRouteChildren)

interface SpeechRouteChildren {
  SpeechDrillIdRoute: typeof SpeechDrillIdRoute
}

const SpeechRouteChildren: SpeechRouteChildren = {
  SpeechDrillIdRoute: SpeechDrillIdRoute,
}

const SpeechRouteWithChildren =
  SpeechRoute._addFileChildren(SpeechRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchetypesRoute: ArchetypesRouteWithChildren,
  BrainRoute: BrainRouteWithChildren,
  DietRoute: DietRoute,
  JournalRoute: JournalRoute,
  MissionsRoute: MissionsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SpeechRoute: SpeechRouteWithChildren,
  SurpriseRoute: SurpriseRoute,
  WatchRoute: WatchRoute,
  FolderSplatRoute: FolderSplatRoute,
  NoteSplatRoute: NoteSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
