/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as ArchetypesRouteImport } from './routes/archetypes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrainHistoryRouteImport } from './routes/brain.history'
import { Route as BrainStudioLaneRouteImport } from './routes/brain.studio.$lane'
import { Route as BrainDrillIdRouteImport } from './routes/brain.drill.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchetypesRoute = ArchetypesRouteImport.update({
  id: '/archetypes',
  path: '/archetypes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainHistoryRoute = BrainHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BrainRoute,
} as any)
const BrainStudioLaneRoute = BrainStudioLaneRouteImport.update({
  id: '/studio/$lane',
  path: '/studio/$lane',
  getParentRoute: () => BrainRoute,
} as any)
const BrainDrillIdRoute = BrainDrillIdRouteImport.update({
  id: '/drill/$id',
  path: '/drill/$id',
  getParentRoute: () => BrainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRoute
  '/brain': typeof BrainRouteWithChildren
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/brain/history': typeof BrainHistoryRoute
  '/brain/drill/$id': typeof BrainDrillIdRoute
  '/brain/studio/$lane': typeof BrainStudioLaneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRoute
  '/brain': typeof BrainRouteWithChildren
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/brain/history': typeof BrainHistoryRoute
  '/brain/drill/$id': typeof BrainDrillIdRoute
  '/brain/studio/$lane': typeof BrainStudioLaneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRoute
  '/brain': typeof BrainRouteWithChildren
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/brain/history': typeof BrainHistoryRoute
  '/brain/drill/$id': typeof BrainDrillIdRoute
  '/brain/studio/$lane': typeof BrainStudioLaneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archetypes'
    | '/brain'
    | '/missions'
    | '/profile'
    | '/settings'
    | '/brain/history'
    | '/brain/drill/$id'
    | '/brain/studio/$lane'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archetypes'
    | '/brain'
    | '/missions'
    | '/profile'
    | '/settings'
    | '/brain/history'
    | '/brain/drill/$id'
    | '/brain/studio/$lane'
  id:
    | '__root__'
    | '/'
    | '/archetypes'
    | '/brain'
    | '/missions'
    | '/profile'
    | '/settings'
    | '/brain/history'
    | '/brain/drill/$id'
    | '/brain/studio/$lane'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchetypesRoute: typeof ArchetypesRoute
  BrainRoute: typeof BrainRouteWithChildren
  MissionsRoute: typeof MissionsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archetypes': {
      id: '/archetypes'
      path: '/archetypes'
      fullPath: '/archetypes'
      preLoaderRoute: typeof ArchetypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain/history': {
      id: '/brain/history'
      path: '/history'
      fullPath: '/brain/history'
      preLoaderRoute: typeof BrainHistoryRouteImport
      parentRoute: typeof BrainRoute
    }
    '/brain/studio/$lane': {
      id: '/brain/studio/$lane'
      path: '/studio/$lane'
      fullPath: '/brain/studio/$lane'
      preLoaderRoute: typeof BrainStudioLaneRouteImport
      parentRoute: typeof BrainRoute
    }
    '/brain/drill/$id': {
      id: '/brain/drill/$id'
      path: '/drill/$id'
      fullPath: '/brain/drill/$id'
      preLoaderRoute: typeof BrainDrillIdRouteImport
      parentRoute: typeof BrainRoute
    }
  }
}

interface BrainRouteChildren {
  BrainHistoryRoute: typeof BrainHistoryRoute
  BrainDrillIdRoute: typeof BrainDrillIdRoute
  BrainStudioLaneRoute: typeof BrainStudioLaneRoute
}

const BrainRouteChildren: BrainRouteChildren = {
  BrainHistoryRoute: BrainHistoryRoute,
  BrainDrillIdRoute: BrainDrillIdRoute,
  BrainStudioLaneRoute: BrainStudioLaneRoute,
}

const BrainRouteWithChildren = BrainRoute._addFileChildren(BrainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchetypesRoute: ArchetypesRoute,
  BrainRoute: BrainRouteWithChildren,
  MissionsRoute: MissionsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
